In [ ]:
# Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

## Data Collection and Analysis

In [5]:
# loading the data from csv file to a Pandas Dataframe
customer_data = pd.read_csv("../data/raw/Mall_Customers.csv")

In [6]:
customer_data.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [7]:
customer_data.tail()

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

In [8]:
customer_data.sample(5)

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
99          100    Male   20                  61                      49
133         134  Female   31                  72                      71
160         161  Female   56                  79                      35
155         156  Female   27                  78                      89
86           87  Female   55                  57                      58

In [9]:
# Finding the number of rows and columns
customer_data.shape

(200, 5)

In [10]:
# getting some informations about the datasets
customer_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    str
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), str(1)
memory usage: 8.9 KB

In [11]:
# Checking for missing values
customer_data.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [12]:
# Checking for duplicate values
customer_data.duplicated().sum()

0

## Choosing the Annual Income Column and Spending Score Column

In [13]:
X = customer_data.iloc[:,[3,4]].values

In [ ]:
X

## Choosing the number of clusters

WCSS -> Within Clusters Sum of Squares

In [16]:
# Finding WCSS value for different number of clusters

In [18]:
wcss = []

In [19]:
for i in range(1,11):
    kmeans = KMeans(n_clusters=i, init = 'k-means++', random_state = 24)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

In [20]:
wcss

[269981.28,
 186362.95600651758,
 106348.37306211118,
 73880.64496247197,
 44448.45544793371,
 37455.984555160285,
 30273.394312070042,
 25388.76002817937,
 22225.448862422803,
 19740.01037035931]